# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'untitled.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Projeto(object):
    def setupUi(self, Projeto):
        if not Projeto.objectName():
            Projeto.setObjectName(u"Projeto")
        Projeto.resize(800, 597)
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(199, 44, 65, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(238, 69, 64, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(160, 23, 67, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(64, 9, 27, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(85, 12, 36, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush6 = QBrush(QColor(0, 0, 0, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush6)
        brush7 = QBrush(QColor(128, 19, 54, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush7)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
        brush8 = QBrush(QColor(255, 255, 220, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush7)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush7)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush7)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
        Projeto.setPalette(palette)
        self.centralwidget = QWidget(Projeto)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(20, 70, 341, 51))
        palette1 = QPalette()
        brush9 = QBrush(QColor(25, 5, 8, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush9)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush9)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        self.pushButton.setPalette(palette1)
        font = QFont()
        font.setFamily(u"Segoe UI")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(440, 70, 341, 51))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush9)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush9)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        self.pushButton_2.setPalette(palette2)
        self.pushButton_2.setFont(font)
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(440, 180, 341, 51))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush9)
        palette3.setBrush(QPalette.Inactive, QPalette.ButtonText, brush9)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        self.pushButton_3.setPalette(palette3)
        self.pushButton_3.setFont(font)
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(20, 300, 341, 51))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.ButtonText, brush9)
        palette4.setBrush(QPalette.Inactive, QPalette.ButtonText, brush9)
        palette4.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        self.pushButton_4.setPalette(palette4)
        self.pushButton_4.setFont(font)
        self.pushButton_5 = QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(20, 180, 341, 51))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.ButtonText, brush9)
        palette5.setBrush(QPalette.Inactive, QPalette.ButtonText, brush9)
        palette5.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        self.pushButton_5.setPalette(palette5)
        self.pushButton_5.setFont(font)
        self.pushButton_6 = QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(440, 300, 341, 51))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.ButtonText, brush9)
        palette6.setBrush(QPalette.Inactive, QPalette.ButtonText, brush9)
        palette6.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        self.pushButton_6.setPalette(palette6)
        self.pushButton_6.setFont(font)
        Projeto.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(Projeto)
        self.statusbar.setObjectName(u"statusbar")
        Projeto.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(Projeto)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 21))
        Projeto.setMenuBar(self.menubar)

        self.retranslateUi(Projeto)

        QMetaObject.connectSlotsByName(Projeto)
    # setupUi

    def retranslateUi(self, Projeto):
        Projeto.setWindowTitle(QCoreApplication.translate("Projeto", u"MainWindow", None))
        self.pushButton.setText(QCoreApplication.translate("Projeto", u"Ir para a p\u00e1gina principal", None))
        self.pushButton_2.setText(QCoreApplication.translate("Projeto", u"Ir para a p\u00e1gina principal", None))
        self.pushButton_3.setText(QCoreApplication.translate("Projeto", u"Ir para a p\u00e1gina principal", None))
        self.pushButton_4.setText(QCoreApplication.translate("Projeto", u"Ir para a p\u00e1gina principal", None))
        self.pushButton_5.setText(QCoreApplication.translate("Projeto", u"Ir para a p\u00e1gina principal", None))
        self.pushButton_6.setText(QCoreApplication.translate("Projeto", u"Ir para a p\u00e1gina principal", None))
    # retranslateUi

